---
title: "Gasoline Price effects on traffic Fatalities in New York City, 2001-2008"
author: "Guoqing Wang"
date: "10/28/2016"
output: html_document
---

```{r loading packages}
setwd("~/Google Drive/Project")
library(dplyr)
library(foreign)
library(utils)
library(readr)
library(ggplot2)
library(xts)
library(readxl)
library(lubridate)
library(reshape)
library(zoo)
library(XML)
library(gridExtra)
library(tsModel)
library(lmtest)
library(MASS)
library(forecast)
library(splines)
```

```{r aggregate accident data,warning=FALSE}
yearlist =2001:2008
accident = vector("list",length(yearlist))
names(accident) = as.character(yearlist)
year_names = as.character(yearlist)
for(i in 1:length(yearlist)){
accident1 = read.dbf(paste0("./data/data",yearlist[i],"/accident.dbf"))
accident[[i]] = accident1
}

data_nyc = vector("list",length = length(yearlist))
for(i in (yearlist-yearlist[1]+1)){
    temp_acci = accident[[i]]
     data_nyc[[i]] = temp_acci%>%filter(STATE== 36 & CITY==4170)%>%group_by(ST_CASE)%>%
      summarise(fatal=sum(FATALS),Year = YEAR,Month = MONTH,Weather = WEATHER)
}
nyc = bind_rows(data_nyc)
nyc1 = nyc%>%group_by(Year,Month)%>% summarise(fatal = sum(fatal))
nyc1$time = c(1:96)
```


```{r gas price & unemployment rate,warning=FALSE}

gas.price = read_excel(path = "./data/nycgas.xls",skip = 2,sheet = 2)
colnames(gas.price) = c("Date", "gas_price")
gas.price = gas.price%>%mutate(Year = year(Date),Month = month(Date))%>%filter(Year>2000&Year<2009)%>% group_by(Year,Month)%>% summarise(gas_price)

gas.price.nyc = data.frame(time = c(1:96),gasprice = gas.price$gas_price)

URnyc_temp=read_excel("./data/nycUR.xls", skip=4,col_names = T)
URnyc = data.frame(time = 1:96,UnempRate = URnyc_temp[300:395,6])
names(URnyc) = c("time", "UnempRate")
```

```{r weather-precipation,warning=FALSE}
weather_temp1 = read.csv("./data/precipitation.csv")

weather = data.frame(time = 1:96, precip=as.numeric(as.vector(t(as.matrix(weather_temp1[,-1])))))


weather_tempera1 = read.csv("./data/temperature.csv")

weather.temp = data.frame(time = 1:96, temperature=as.numeric(as.vector(t(as.matrix(weather_tempera1[,-1])))))

data.nyc = inner_join(nyc1,gas.price.nyc)%>%inner_join(.,weather)%>%inner_join(.,URnyc)%>%inner_join(., weather.temp)
data.nyc$months = as.Date(as.yearmon(paste(rep(2001:2008, each = 12),rep(1:12,8),sep = "-")))
data.nyc$UnempRate = data.nyc$UnempRate/100
```



```{r EDA,warning=FALSE}
#dev.off()
fig1 = ggplot(data=data.nyc,aes(months,fatal))+geom_point() + geom_smooth(method = 'glm',formula = y~ns(x,8*4),method.args = list(family = poisson))+ylab("Fatality")+xlab("Month")+ggtitle("(a) Fatality Vs. Time")

fig2 = ggplot(data.nyc,aes(gasprice,fatal))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,1),method.args = list(family = poisson))+ylab("Fatality")+xlab("Gasoline Price ($)")+ggtitle("(b) Fatality Vs. Gasoline Price")

fig3 = ggplot(data.nyc,aes(precip,fatal))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,3),method.args = list(family = poisson))+ylab("Fatality")+xlab("Precipitation (mm)")+ggtitle("(c) Fatality Vs. Precipitation")


fig4 = ggplot(data.nyc,aes(UnempRate,fatal))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,3),method.args = list(family = poisson))+ylab("Fatality")+xlab("Unemployment Rate (%)")+ggtitle("(c) Fatality Vs. Unemployment Rate")
fig5 = ggplot(data.nyc,aes(temperature,fatal))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,3),method.args = list(family = poisson))+ylab("Fatality")+xlab("Temperature (F)")+ggtitle("(d) Fatality Vs. Temperature")
fig6 = ggplot(data.nyc,aes(months,gasprice))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,8*3),method.args = list(family = poisson))+ylab("gasprice")+xlab("Months")

#ggplot(data.nyc,aes(months,UnempRate))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,5),method.args = list(family = poisson))+ylab("gasprice")+xlab("Months")

#ggplot(data.nyc,aes(months,gasprice))+geom_point()+geom_smooth(method = 'glm',formula = y~ns(x,5),method.args = list(family = poisson))+ylab("gasprice")+xlab("Months")

grid.arrange(fig1,fig2,fig5,fig4,ncol=2)
```


```{r model,warning=FALSE}

fit1 = glm(fatal ~ ns(time,8*4), data = data.nyc, family = "poisson")
aic = 1:12


fit2 = glm(fatal ~ Lag(gasprice,0:1)+temperature + ns(precip,3)+ ns(UnempRate,3)+ns(time,8*4), data = data.nyc, family = "poisson")

fit3 = glm(fatal ~ Lag(gasprice,0:1)+temperature+ns(time,8*4), data = data.nyc, family = "poisson")
#summary(fit3)

anova(fit3,fit2,test = "LRT") # use fit3

fit4= glm(fatal ~ Lag(gasprice,0:1)+temperature+ns(time,8*4), data = data.nyc, family = "quasipoisson")
#summary(fit4)

disper = summary(fit4)$dispersion
```

```{r model check,warning=FALSE}
# draw fitted value

newdata = data.frame(gasprice = rep(2.5,96),temperature = rep(50,96), time = 1:96)
newdata$pred1 = predict(fit4,newdata = newdata,type = "response")
data.new = data.nyc
data.new$pred = newdata$pred1

fitplot1 = ggplot(data.new,aes(x=months))+geom_point(aes(y=fatal))+geom_smooth(aes(y = fatal, colour = "Fatality"),method = 'glm',formula = y~ns(x,8*4),method.args = list(family = poisson))+geom_line(aes(y=pred,colour= "Prediction"))+ylab("Fatality")+xlab("Month")+ggtitle("(a) Fitted Fatality Vs. Time")+scale_colour_manual("", 
                      breaks = c("Fatality", "Prediction"),
                      values = c("blue", "red"))

newdata1 = data.frame(gasprice = seq(1,4,length.out = 96),temperature = rep(67,96), time = 40)
data.new$pred1 = predict(fit4,newdata = newdata1,type = "response")

fitplot2 = ggplot(data.new,aes(x = gasprice))+geom_point(aes(y=fatal))+geom_smooth(aes(y=fatal,colour= "Fatality"),method = 'glm',formula = y~ns(x,3),method.args = list(family = poisson))+geom_smooth(aes(y=pred1,colour= "Prediction"))+ylab("Fatality")+xlab("Gasoline Price")+ggtitle("(b) Fitted Fatality Vs. Price")+scale_colour_manual("", 
                      breaks = c("Fatality", "Prediction"),
                      values = c("blue", "red"))

grid.arrange(fitplot1,fitplot2,ncol =1)

par(mfrow = c(2,2))
plot(fit4)

# check independence
resid = residuals(fit4,"deviance")
lag.plot(resid,9,do.lines=FALSE)
par(mfrow=c(1,2))
Acf(resid,lag.max = 9)
plot(resid,xlab="Months",ylab="Residuals",pch=".")
lines(resid)

#check influential points
colinearity = symnum(cor(data.nyc[,c(3:8)]))

plot(dffits(fit4))
length(which(abs(dffits(fit4))>1.3))

fit4.rm = glm(fatal ~ Lag(gasprice,0:1)+temperature +ns(time,8*4), data = data.nyc[which(abs(dffits(fit4))<=1.3),], family = "quasipoisson")

summ_fit4.rm = summary(fit4.rm)

#print in the latex format
#library(knitr)
#library(xtable)
#coeff = xtable(summary(fit4)$coefficients[1:4,])
#print(x =coeff, type="latex")

coef_gas = summary(fit4)$coefficients[2:3,1:2]
conf_gas = confint(fit4)[2:3,]
response = 100*(exp(coef_gas)-1)
response_gas= 100*(exp(conf_gas)-1)

sumcoef_gas = sum(coef_gas[,1])
respTotal = 100*(exp(sumcoef_gas)-1)

conf_sum=sumcoef_gas+c(-1,1)*1.96*sqrt(sum(vcov(fit4)[2:4,2:4][lower.tri(vcov(fit4)[2:4,2:4])==F]))
conf_summm=-100*(exp(conf_sum)-1)
```

